-- MySQL Script generated by MySQL Workbench
-- Thu Apr 11 22:03:54 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ead02-Hadson
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ead02-Hadson
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ead02-Hadson` DEFAULT CHARACTER SET utf8 ;
USE `ead02-Hadson` ;

-- -----------------------------------------------------
-- Table `ead02-Hadson`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ead02-Hadson`.`empresa` (
  `idempresa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `gestao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idempresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ead02-Hadson`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ead02-Hadson`.`cargos` (
  `idcargos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcargos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ead02-Hadson`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ead02-Hadson`.`funcionario` (
  `idfuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(11) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `telefone` INT NULL,
  `empresa_idempresa` INT NOT NULL,
  `cargos_idcargos` INT NOT NULL,
  PRIMARY KEY (`idfuncionario`),
  INDEX `fk_funcionario_empresa_idx` (`empresa_idempresa` ASC),
  INDEX `fk_funcionario_cargos1_idx` (`cargos_idcargos` ASC),
  CONSTRAINT `fk_funcionario_empresa`
    FOREIGN KEY (`empresa_idempresa`)
    REFERENCES `ead02-Hadson`.`empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_cargos1`
    FOREIGN KEY (`cargos_idcargos`)
    REFERENCES `ead02-Hadson`.`cargos` (`idcargos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ead02-Hadson`.`projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ead02-Hadson`.`projetos` (
  `idprojetos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `dtinicio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprojetos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ead02-Hadson`.`trabalho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ead02-Hadson`.`trabalho` (
  `funcionario_idfuncionario` INT NOT NULL,
  `projetos_idprojetos` INT NOT NULL,
  PRIMARY KEY (`funcionario_idfuncionario`, `projetos_idprojetos`),
  INDEX `fk_funcionario_has_projetos_projetos1_idx` (`projetos_idprojetos` ASC),
  INDEX `fk_funcionario_has_projetos_funcionario1_idx` (`funcionario_idfuncionario` ASC),
  CONSTRAINT `fk_funcionario_has_projetos_funcionario1`
    FOREIGN KEY (`funcionario_idfuncionario`)
    REFERENCES `ead02-Hadson`.`funcionario` (`idfuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_has_projetos_projetos1`
    FOREIGN KEY (`projetos_idprojetos`)
    REFERENCES `ead02-Hadson`.`projetos` (`idprojetos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ead02-Hadson`.`salario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ead02-Hadson`.`salario` (
  `idsalario` INT NOT NULL AUTO_INCREMENT,
  `qntd` DECIMAL(10,2) NOT NULL,
  `cargos_idcargos` INT NOT NULL,
  PRIMARY KEY (`idsalario`),
  INDEX `fk_salario_cargos1_idx` (`cargos_idcargos` ASC),
  CONSTRAINT `fk_salario_cargos1`
    FOREIGN KEY (`cargos_idcargos`)
    REFERENCES `ead02-Hadson`.`cargos` (`idcargos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
